version: "3.8"
services:
  flask-api:
    build:
      context: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  springboot-api:
    build:
      context:  ./../../Documents/workspace-spring-tool-suite-4-4.22.0.RELEASE/ms-task
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge